# Generated by Django 4.1.7 on 2023-07-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='image', max_length=255),
        ),
    ]
