# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10zd9b2jot3mb-f10UWZZZFnBRXW-T7QA
"""
import json
from gradio_client import Client

client = Client("https://deepconclusions-tomato.hf.space/")
result = client.predict(
				"https://th.bing.com/th/id/OIP.pv9ajC5bZLmZ0hdcAAayUwHaJ4?pid=ImgDet&rs=1",	# str (filepath or URL to image) in 'img' Image component
				api_name="/predict"
)

with open(result, 'r') as file:
    json_data = json.load(file)

print(json_data['label'])
print(json_data['confidences'])
